### ISSUE TITLE
Missing help in JAR

### ISSUE THREAD

**Issue by lupino3** [EduMIPS64/edumips64#476]
The code in `master` produces a JAR with no help. Here is the exception (from a different commit, as I am already doing `git bisect`):

```
EduMIPS64 version 1.2.8 (codename: "NLMS", git revision master@442cd04, built on 2020-10-20T10:24:10.468169) - Ciao 'mbare.
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javax/help/HelpSetException
        at org.edumips64.Main.lambda$createMenuBar$18(Main.java:926)
```
